# Spring boot application
spring:
  application:
    name: myshop-service-upload
server:
  port: 8888
fastdfs.base.url: http://192.168.161.136:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 192.168.161.136:22122