version: '3.1'
services:
  myshop-serivce-user-consumer:
    restart: always
    image: 192.168.161.136:5000/myshop-service-user-consumer:v1.0.0
    container_name: myshop-service-user-consumer
    ports:
      - 8601:8601
      - 8701:8701
networks:
  default:
    external:
      name: dubbo